### ISSUE TITLE
remove extra variable

### ISSUE THREAD

**Issue by JonathanSafer** [Harlem-Launch-Alliance/Catalyst-2#111]
near the top of `main.ino`, there's an unused variable declared called `apogeeReached`. This can cause quite a bit of confusion because there's another variable with the same name used later on that is unrelated. This unused variable should be deleted. Also, the `//variables` comment can be deleted since there won't be any global variables defined at that location.

**Comment by Mannuel25** [comment]
Hello @JonathanSafer , I'd love to take this up. Kindly assign it to me.

**Comment by JonathanSafer** [comment]
Hi @Mannuel25, we are limiting contributions to this repository to [HLA](https://www.hla.nyc/) members only at this time

**Comment by Mannuel25** [comment]
Okay, thanks.
