### ISSUE TITLE
Prevent instant transition from ascending to post flight

### ISSUE THREAD

**Issue by JonathanSafer** [Harlem-Launch-Alliance/Catalyst-2#77]
If there was an altimeter failure or a very short flight, there is a slight risk that the data backup is skipped. This can be addressed by changing `static int lastAlt` to `-100` in `runDescending()` in `main.ino`. This will ensure that the first landing check always fails, so there will always be at least one data backup.

**Comment by LoriMoses** [comment]
May need assistance .

**Comment by LoriMoses** [comment]
I will be at the next club meeting .

**Comment by JonathanSafer** [comment]
The solution in #128 unintentionally takes care of this issue as well
